version: "3"

services:
  vue:
    build:
      context: ./containers
      dockerfile: vue_dockerfile
    container_name: vue_develop
    volumes:
      - ./frontend:/vue
    ports:
      - 8080:8080
    tty: true
  golang:
    image: golang:latest
    container_name: go_develop
    volumes:
      - ./backend:/go/src/server
    ports:
      - 8000:8080
    tty: true

  authentication:
    image: golang:latest
    container_name: auth_service
    networks:
      - backend
    environment:
      - PORT=8080
      - SECRET=secret
    volumes:
      - ./backend/authentication:/go/src/authentication
    ports:
      - 8000:8080
    tty: true
    command: "/go/src/authentication/launch.sh"

  cache:
    image: redis:latest
    container_name: cache
    networks:
      - backend
    ports:
      - 6379:6379

  database:
    image: postgres:latest
    container_name: relation_db_server
    networks:
      - backend
    environment:
      POSTGRES_USER: livewithchat
      POSTGRES_PASSWORD: default
      POSTGRES_DB: livewithchat
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/

networks:
  frontend:
  backend:
volumes:
  database-data:
