FROM node:alpine as builder

WORKDIR /vue-ui

RUN yarn global add @vue/cli

COPY package*.json ./
RUN yarn install

COPY . .
RUN yarn build


FROM nginx:stable-alpine as production-build
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./.nginx/live-with-chat.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /vue-ui/dist /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]